### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by TonyStark** [kevin125/MT7601U_Linux_AP_STA#1]
```
/home/stark/learn/mi/MT7601U_Linux_AP_STA/MT7601U_LinuxAP_3.0.0.1_20130802/include/os/rt_linux.h:490:35: note: in expansion of macro ‘RT_GET_OS_PID’
 #define RTMP_GET_OS_PID(_a, _b)   RT_GET_OS_PID(_a, _b)
                                   ^
/home/stark/learn/mi/MT7601U_Linux_AP_STA/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/../../ap/ap_cfg.c:9957:2: note: in expansion of macro ‘RTMP_GET_OS_PID’
  RTMP_GET_OS_PID(pObj->IappPid, IappPid);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:316: recipe for target '/home/stark/learn/mi/MT7601U_Linux_AP_STA/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/../../ap/ap_cfg.o' failed
make[2]: *** [/home/stark/learn/mi/MT7601U_Linux_AP_STA/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/../../ap/ap_cfg.o] Error 1
Makefile:1550: recipe for target '_module_/home/stark/learn/mi/MT7601U_Linux_AP_STA/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux' failed
make[1]: *** [_module_/home/stark/learn/mi/MT7601U_Linux_AP_STA/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-43-generic'
Makefile:387: recipe for target 'LINUX' failed
make: *** [LINUX] Error 2

```

**Comment by kevin125** [comment]
Please check the Makefile, maybe it is warning threat as errors.
If the error still happen, please tell me your env, such as os gcc...I will fix it in the next week.

**Comment by TonyStark** [comment]
Always get error
i have installed kernel header too, but no solution
i have ubuntu 16.04
`Linux ubuntu 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) `
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
loook this was compiled easily but not stable and not station mode>>https://github.com/THLIVSQAZ/MT7601U
maybe it could help you to fix problem

**Comment by kevin125** [comment]
I'm travelling, please wait about a week.

**Comment by TonyStark** [comment]
No problem bro
Have a safe journey ;D

**Comment by kevin125** [comment]
Do you build from tar ball or source code directly?

The tar ball is the original source with build errors.

Fix commit: https://github.com/kevin125/MT7601U_Linux_AP_STA/commit/c0ab549584a941627f5c5ccb07db414e7af99bfb

Please check the file "os/linux/config.mk"
Line 210:
WFLAGS += -Wno-error -Wno-error=date-time -Wno-unused-variable

You can also goole for "cc1: some warnings being treated as errors"
This is my  result:
https://stackoverflow.com/questions/11561261/how-to-compile-without-warnings-being-treated-as-errors

**Comment by TonyStark** [comment]
i have latest build, downloaded using git clone
also made changes in config.mk as per your suggestion
but still getting error (not warning type)
here it it>>

> /home/stark/learn/mi/MT7601U_Linux_AP_STA/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/../../ap/ap_cfg.c:7263:27: **error: passing argument 2 of ‘RtmpDrvAllRFPrint’ from incompatible pointer type** [-Werror=incompatible-pointer-types]
>    RtmpDrvAllRFPrint(NULL, msg, strlen(msg));
> 

Full log>> https://paste.ofcode.org/hvD7cB4JqYSQex8TvJFUUd

**Comment by kevin125** [comment]
the same error

please check the config.mk and remove -Werror

**Comment by TonyStark** [comment]
Not helped
still same error

**Comment by kevin125** [comment]
diff --git a/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/config.mk b/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/config.mk
index 9680b78..bf138af 100644
--- a/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/config.mk
+++ b/MT7601U_LinuxAP_3.0.0.1_20130802/os/linux/config.mk
@@ -208,6 +208,8 @@ WFLAGS := -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT  -DLINUX -Wall
 WFLAGS += -DSYSTEM_LOG_SUPPORT -DRT28xx_MODE=$(RT28xx_MODE) -DCHIPSET=$(MODULE) -DRESOURCE_PRE_ALLOC
 #WFLAGS += -DFPGA_MODE
 WFLAGS += -Wno-error=date-time -Wno-unused-variable
+WFLAGS += -Wno-error=incompatible-pointer-types
+WFLAGS += -Wno-error=implicit-function-declaration
 WFLAGS += -I$(RT28xx_DIR)/include

**Comment by TonyStark** [comment]
Thanks
successfully compiled, but i think it crash kernel
after loading mt7601Uap driver, when i open my android local IP in computer browser everything hanged
no cursor moving, so it crashed.
but dont know why this happen by putting android local ip (http://10.42.0.254:8999) in browser

**Comment by kevin125** [comment]
I found that too, but i cannot resolve it😂

**Comment by TonyStark** [comment]
anyway no problem
thank you :)
