### ISSUE TITLE
in kernel up 4.15

### ISSUE THREAD

**Issue by sasha5434** [kevin125/MT7601U_Linux_AP_STA#2]
for ap mode

in /os/linux/rt_linux.c replace this function to

	if (!timer_pending(pTimer)) {
		timer_setup(pTimer, function, 0); 
	}

and in end of /os/linux/config.mk

EXTRA_CFLAGS+=-Wno-implicit-function-declaration
EXTRA_CFLAGS+=-Wno-incompatible-pointer-types

work in ubuntu 18.04 LTS

**Comment by kevin125** [comment]
Thanks for you comments!
